import os
import re
import json
import arxiv
import yaml
import logging
import argparse
import datetime
import random
import time
import requests

logging.basicConfig(format='[%(asctime)s %(levelname)s] %(message)s',
                    datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

github_url = "https://api.github.com/search/repositories"
arxiv_url = "https://arxiv.org/"

def load_config(config_file:str) -> dict:
    '''
    config_file: input config file path
    return: a dict of configuration
    '''
    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        EXCAPE = '\"'
        QUOTA = '' # NO-USE
        OR = ' OR ' # TODO
        def parse_filters(filters:list):
            ret = ''
            for idx in range(0,len(filters)):
                filter = filters[idx]
                if len(filter.split()) > 1:
                    ret += (EXCAPE + filter + EXCAPE)
                else:
                    ret += (QUOTA + filter + QUOTA)
                if idx != len(filters) - 1:
                    ret += OR
            return ret
        for k,v in config['keywords'].items():
            keywords[k] = parse_filters(v['filters'])
        return keywords
    with open(config_file,'r') as f:
        config = yaml.load(f,Loader=yaml.FullLoader)
        config['kv'] = pretty_filters(**config)
        logging.info(f'config = {config}')
    return config

def get_authors(authors, first_author = False):
    output = str()
    if first_author == False:
        output = ", ".join(str(author) for author in authors)
    else:
        output = authors[0]
    return output
def sort_papers(papers):
    output = dict()
    keys = list(papers.keys())
    keys.sort(reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output
import requests

def get_code_link(qword:str) -> str:
    """
    This short function was auto-generated by ChatGPT.
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    # query = f"arxiv:{arxiv_id}"
    query = f"{qword}"
    params = {
        "q": query,
        "sort": "stars",
        "order": "desc"
    }
    r = requests.get(github_url, params=params)
    results = r.json()
    code_link = None
    if results["total_count"] > 0:
        code_link = results["items"][0]["html_url"]
    return code_link

def get_daily_papers(topic,query="slam", max_results=2, client=None,
                     retry_backoff_seconds=None):
    """
    @param topic: str
    @param query: str
    @return paper_with_code: dict
    """
    # output
    content = dict()
    content_to_web = dict()
    paper_details = []
    search_engine = arxiv.Search(
        query = query,
        max_results = max_results,
        sort_by = arxiv.SortCriterion.SubmittedDate
    )

    if client is None:
        client = arxiv.Client(page_size=max_results)
    retry_backoff_seconds = retry_backoff_seconds or []
    results = None
    for attempt in range(len(retry_backoff_seconds) + 1):
        try:
            results = list(client.results(search_engine))
            break
        except arxiv.HTTPError as error:
            is_rate_limited = getattr(error, "status", None) == 429
            if not is_rate_limited or attempt == len(retry_backoff_seconds):
                raise
            wait_seconds = retry_backoff_seconds[attempt]
            logging.warning(
                "arXiv rate limit for %s; retrying this category in %s seconds",
                topic,
                wait_seconds,
            )
            time.sleep(wait_seconds)

    for result in results:

        paper_id            = result.get_short_id()
        paper_title         = result.title
        paper_url           = result.entry_id
        paper_abstract      = result.summary.replace("\n"," ")
        paper_authors       = get_authors(result.authors)
        paper_first_author  = get_authors(result.authors,first_author = True)
        primary_category    = result.primary_category
        publish_time        = result.published.date()
        update_time         = result.updated.date()
        comments            = result.comment

        logging.info(f"Time = {update_time} title = {paper_title} author = {paper_first_author}")

        # eg: 2108.09112v1 -> 2108.09112
        ver_pos = paper_id.find('v')
        if ver_pos == -1:
            paper_key = paper_id
        else:
            paper_key = paper_id[0:ver_pos]
        paper_url = arxiv_url + 'abs/' + paper_key

        # Since PapersWithCode API is deprecated, we no longer fetch code links
        # Papers will be listed without code links
        content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|null|\n".format(
               update_time,paper_title,paper_first_author,paper_key,paper_url)
        content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({})".format(
               update_time,paper_title,paper_first_author,paper_url,paper_url)

        paper_details.append({
            "paper_id": paper_key,
            "title": paper_title,
            "authors": paper_authors,
            "first_author": str(paper_first_author),
            "published": str(publish_time),
            "updated": str(update_time),
            "url": paper_url,
            "categories": [topic],
        })

        # TODO: select useful comments
        comments = None
        if comments != None:
            content_to_web[paper_key] += f", {comments}\n"
        else:
            content_to_web[paper_key] += f"\n"

    data = {topic:content}
    data_web = {topic:content_to_web}
    return data,data_web,paper_details

def load_existing_paper_ids(filename):
    """Return all version-free arXiv IDs already stored in the main JSON file."""
    with open(filename,"r") as f:
        content = f.read()
    if not content:
        return set()
    data = json.loads(content)
    return {
        re.sub(r'v\d+$', '', paper_id)
        for papers in data.values()
        for paper_id in papers.keys()
    }

def ordered_categories(data, category_order=None):
    """Return configured categories first, followed by unknown historical ones."""
    category_order = category_order or []
    ordered = [category for category in category_order if category in data]
    ordered.extend(category for category in data if category not in ordered)
    return ordered

def collect_new_papers(paper_details, existing_ids, deduplicate=True):
    """Collect papers absent from the pre-update database for daily notification."""
    if not deduplicate:
        return [paper for paper in paper_details if paper["paper_id"] not in existing_ids]

    new_papers = {}
    for paper in paper_details:
        paper_id = paper["paper_id"]
        if paper_id in existing_ids:
            continue
        if paper_id not in new_papers:
            new_papers[paper_id] = paper.copy()
            new_papers[paper_id]["categories"] = list(paper["categories"])
        else:
            for category in paper["categories"]:
                if category not in new_papers[paper_id]["categories"]:
                    new_papers[paper_id]["categories"].append(category)
    return list(new_papers.values())

def write_daily_notification(filename, papers, category_order, config):
    """Write a Markdown body that the workflow can post to a subscribed issue."""
    if not filename:
        return

    # Avoid reusing a stale notification when the same output path is reused.
    with open(filename,"w") as f:
        pass

    notification_config = config.get("notifications", {}).get("github_issue", {})
    if not notification_config.get("enabled", False):
        return
    if not papers and not notification_config.get("notify_on_empty", False):
        return

    today = datetime.date.today().isoformat()
    lines = [f"## AI4Bio ArXiv Daily · {today}", ""]
    if not papers:
        lines.extend(["今日无新增论文。", ""])
    else:
        lines.extend([f"今日新增 {len(papers)} 篇论文。", ""])
        categories = {category: [] for category in category_order}
        for paper in papers:
            primary_category = next(
                (category for category in category_order
                 if category in paper["categories"]),
                paper["categories"][0],
            )
            categories.setdefault(primary_category, []).append(paper)

        for category in ordered_categories(categories, category_order):
            category_papers = categories[category]
            if not category_papers:
                continue
            lines.extend([f"### {category}", ""])
            category_papers.sort(
                key=lambda paper: (paper["updated"], paper["paper_id"]),
                reverse=True,
            )
            for index, paper in enumerate(category_papers, 1):
                matched_categories = "；".join(paper["categories"])
                lines.extend([
                    f'{index}. **{paper["title"]}**',
                    f'   - 第一作者：{paper["first_author"]} et al.',
                    f'   - 发布日期：{paper["published"]}',
                    f'   - 分类：{matched_categories}',
                    f'   - [arXiv:{paper["paper_id"]}]({paper["url"]})',
                    "",
                ])

        repository = os.environ.get(
            "GITHUB_REPOSITORY",
            f'{config.get("user_name", "")}/{config.get("repo_name", "")}',
        ).strip("/")
        if repository:
            lines.extend([
                f"[查看完整论文列表](https://github.com/{repository})",
                "",
            ])

    with open(filename,"w") as f:
        f.write("\n".join(lines))
    logging.info(f"Daily notification written to {filename}")

def update_paper_links(filename):
    '''
    weekly update paper links in json file
    '''
    def parse_arxiv_string(s):
        parts = s.split("|")
        date = parts[1].strip()
        title = parts[2].strip()
        authors = parts[3].strip()
        arxiv_id = parts[4].strip()
        code = parts[5].strip()
        arxiv_id = re.sub(r'v\d+', '', arxiv_id)
        return date,title,authors,arxiv_id,code

    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

        json_data = m.copy()

        for keywords,v in json_data.items():
            logging.info(f'keywords = {keywords}')
            for paper_id,contents in v.items():
                contents = str(contents)

                update_time, paper_title, paper_first_author, paper_url, code_url = parse_arxiv_string(contents)

                contents = "|{}|{}|{}|{}|{}|\n".format(update_time,paper_title,paper_first_author,paper_url,code_url)
                json_data[keywords][paper_id] = str(contents)
                logging.info(f'paper_id = {paper_id}, contents = {contents}')

                # PapersWithCode API is deprecated, skip code link updates
                # Papers will keep their existing null code links
                logging.info(f'Skipping code link update for paper_id = {paper_id} (PapersWithCode API deprecated)')
        # dump to json file
        with open(filename,"w") as f:
            json.dump(json_data,f)

def update_json_file(filename,data_dict):
    '''
    daily update json file using data_dict
    '''
    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

    json_data = m.copy()

    # update papers in each keywords
    for data in data_dict:
        for keyword in data.keys():
            papers = data[keyword]

            if keyword in json_data.keys():
                json_data[keyword].update(papers)
            else:
                json_data[keyword] = papers

    with open(filename,"w") as f:
        json.dump(json_data,f)

def json_to_md(filename,md_filename,
               task = '',
               to_web = False,
               use_title = True,
               use_tc = True,
               show_badge = True,
               use_b2t = True,
               category_order = None):
    """
    @param filename: str
    @param md_filename: str
    @return None
    """
    def pretty_math(s:str) -> str:
        ret = ''
        match = re.search(r"\$.*\$", s)
        if match == None:
            return s
        math_start,math_end = match.span()
        space_trail = space_leading = ''
        if s[:math_start][-1] != ' ' and '*' != s[:math_start][-1]: space_trail = ' '
        if s[math_end:][0] != ' ' and '*' != s[math_end:][0]: space_leading = ' '
        ret += s[:math_start]
        ret += f'{space_trail}${match.group()[1:-1].strip()}${space_leading}'
        ret += s[math_end:]
        return ret

    DateNow = datetime.date.today()
    DateNow = str(DateNow)
    DateNow = DateNow.replace('-','.')

    with open(filename,"r") as f:
        content = f.read()
        if not content:
            data = {}
        else:
            data = json.loads(content)

    # clean README.md if daily already exist else create it
    with open(md_filename,"w+") as f:
        pass

    # write data into README.md
    with open(md_filename,"a+") as f:

        if (use_title == True) and (to_web == True):
            f.write("---\n" + "layout: default\n" + "---\n\n")

        # if show_badge == True:
        #     f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
        #     f.write(f"[![Forks][forks-shield]][forks-url]\n")
        #     f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
        #     f.write(f"[![Issues][issues-shield]][issues-url]\n\n")

        if use_title == True:
            #f.write(("<p align="center"><h1 align="center"><br><ins>ai4bio-ARXIV-DAILY"
            #         "</ins><br>Automatically Update ai4bio Papers Daily</h1></p>\n"))
            f.write("## Updated on " + DateNow + "\n")
        else:
            f.write("> Updated on " + DateNow + "\n")

        # TODO: add usage
        f.write("> Usage instructions: [here](./docs/README.md#usage)\n\n")

        #Add: table of contents
        if use_tc == True:
            f.write("<details>\n")
            f.write("  <summary>Table of Contents</summary>\n")
            f.write("  <ol>\n")
            for keyword in ordered_categories(data, category_order):
                day_content = data[keyword]
                if not day_content:
                    continue
                kw = keyword.replace(' ','-')
                f.write(f"    <li><a href=#{kw.lower()}>{keyword}</a></li>\n")
            f.write("  </ol>\n")
            f.write("</details>\n\n")

        for keyword in ordered_categories(data, category_order):
            day_content = data[keyword]
            if not day_content:
                continue
            # the head of each part
            f.write(f"## {keyword}\n\n")

            if use_title == True :
                if to_web == False:
                    f.write("|Publish Date|Title|Authors|PDF|Code|\n" + "|---|---|---|---|---|\n")
                else:
                    f.write("| Publish Date | Title | Authors | PDF | Code |\n")
                    f.write("|:---------|:-----------------------|:---------|:------|:------|\n")

            # sort papers by date
            day_content = sort_papers(day_content)

            for _,v in day_content.items():
                if v is not None:
                    f.write(pretty_math(v)) # make latex pretty

            f.write(f"\n")

            #Add: back to top
            if use_b2t:
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")

        if show_badge == True:
            # we don't like long string, break it!
            f.write((f"[contributors-shield]: https://img.shields.io/github/"
                     f"contributors/Vincentqyw/ai4bio-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[contributors-url]: https://github.com/Vincentqyw/"
                     f"ai4bio-arxiv-daily/graphs/contributors\n"))
            f.write((f"[forks-shield]: https://img.shields.io/github/forks/Vincentqyw/"
                     f"ai4bio-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[forks-url]: https://github.com/Vincentqyw/"
                     f"ai4bio-arxiv-daily/network/members\n"))
            f.write((f"[stars-shield]: https://img.shields.io/github/stars/Vincentqyw/"
                     f"ai4bio-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[stars-url]: https://github.com/Vincentqyw/"
                     f"ai4bio-arxiv-daily/stargazers\n"))
            f.write((f"[issues-shield]: https://img.shields.io/github/issues/Vincentqyw/"
                     f"ai4bio-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[issues-url]: https://github.com/Vincentqyw/"
                     f"ai4bio-arxiv-daily/issues\n\n"))

    logging.info(f"{task} finished")

def demo(**config):
    # TODO: use config
    data_collector = []
    data_collector_web= []
    paper_details = []

    keywords = config['kv']
    max_results = config['max_results']
    publish_readme = config['publish_readme']
    publish_gitpage = config['publish_gitpage']
    publish_wechat = config['publish_wechat']
    show_badge = config['show_badge']
    category_order = config.get('category_order', list(keywords.keys()))
    arxiv_client = arxiv.Client(
        page_size=max_results,
        delay_seconds=config.get('arxiv_delay_seconds', 10),
        num_retries=config.get('arxiv_num_retries', 2),
    )

    b_update = config['update_paper_links']
    logging.info(f'Update Paper Link = {b_update}')
    if config['update_paper_links'] == False:
        initial_jitter = config.get('arxiv_initial_jitter_seconds', 0)
        if os.environ.get('GITHUB_ACTIONS') == 'true' and initial_jitter > 0:
            wait_seconds = random.uniform(0, initial_jitter)
            logging.info(
                "Waiting %.1f seconds before the first arXiv request",
                wait_seconds,
            )
            time.sleep(wait_seconds)

        existing_ids = load_existing_paper_ids(config['json_readme_path'])
        logging.info(f"GET daily papers begin")
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web, details = get_daily_papers(
                topic, query=keyword, max_results=max_results,
                client=arxiv_client,
                retry_backoff_seconds=config.get(
                    'arxiv_retry_backoff_seconds', [60, 180, 300]))
            data_collector.append(data)
            data_collector_web.append(data_web)
            paper_details.extend(details)
            print("\n")
        logging.info(f"GET daily papers end")

        notification_config = config.get('notifications', {}).get('github_issue', {})
        new_papers = collect_new_papers(
            paper_details,
            existing_ids,
            notification_config.get('deduplicate_across_categories', True),
        )
        write_daily_notification(
            config.get('notification_output'),
            new_papers,
            category_order,
            config,
        )

    # 1. update README.md file
    if publish_readme:
        json_file = config['json_readme_path']
        md_file   = config['md_readme_path']
        # update paper links
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            # update json data
            update_json_file(json_file,data_collector)
        # json data to markdown
        json_to_md(json_file,md_file, task ='Update Readme', \
            show_badge = show_badge, category_order = category_order)

    # 2. update docs/index.md file (to gitpage)
    if publish_gitpage:
        json_file = config['json_gitpage_path']
        md_file   = config['md_gitpage_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            update_json_file(json_file,data_collector)
        json_to_md(json_file, md_file, task ='Update GitPage', \
            to_web = True, show_badge = show_badge, \
            use_tc=False, use_b2t=False, category_order = category_order)

    # 3. Update docs/wechat.md file
    if publish_wechat:
        json_file = config['json_wechat_path']
        md_file   = config['md_wechat_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            update_json_file(json_file, data_collector_web)
        json_to_md(json_file, md_file, task ='Update Wechat', \
            to_web=False, use_title= False, show_badge = show_badge, \
            category_order = category_order)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config_path',type=str, default='config.yaml',
                            help='configuration file path')
    parser.add_argument('--update_paper_links', default=False,
                        action="store_true",help='whether to update paper links etc.')
    parser.add_argument('--notification-output', default=None,
                        help='temporary Markdown file for a daily issue comment')
    args = parser.parse_args()
    config = load_config(args.config_path)
    config = {
        **config,
        'update_paper_links': args.update_paper_links,
        'notification_output': args.notification_output,
    }
    demo(**config)
